### ISSUE TITLE
remove dependency on tomopy

### ISSUE THREAD

**Issue by jangarrevoet** [gmysage/pyxas#1]
Hi,
since it is a XAS package this tomopy package should not be a dependency. The paper mentions that you can do 3D in an extension. Since it is an extension I would like to see tomopy removed so that users can also use the XAS functionality without having to deal with the tomopy dependency.
thanks,
Jan

**Comment by gmysage** [comment]
Yes. I agree. Tomopy dependence has been removed. 
In addition, 3D (or batch processing) has been incorporated into main gui.

**Comment by jangarrevoet** [comment]
thanks!
